### ISSUE TITLE
[Feature Request] Non obstructive hole

### ISSUE THREAD

**Issue by jlnrrg** [Apparence-io/pal-widgets#2]
I do not know if this is even possible and would like to here your opinion on this.
Lets take your example project. At this moment the overlay encapsulates the FAB button. 
If I try to hit the FAB button, the overlay vanishes.

So my question is, would it be possible:
1. to absorb the tab, so the overlay does not vanish (only on the cancel or confirm button)
2. to pass the tab through, so the tab action is actually performed on the FAB.

**Comment by jlnrrg** [comment]
Regarding the 1. point I would assume providing `() => null` to the `onTapAnchor` of `AnchoredHelper` to behave like this.

**Comment by g-apparence** [comment]
If I'm correct, you want to 
1 - prevent closing the onboarding when user tap on the anchor?
You're right by default this should do nothing. 
Edit : tested this doesn't perform the action. And by default onTapAnchor is null.
2 - perform your action under the anchor when user press it? 
For this point I think you can call your action using ```onTapAnchor```.
I didn't make it fully transparent(action under the overlay triggered directly) because of the animation. Making it, this would have perform the action (like going on another page) before the fade out animation is fully done. 

Sorry for late reply.
