### ISSUE TITLE
initState display multiple overlays after each other

### ISSUE THREAD

**Issue by jlnrrg** [Apparence-io/pal-widgets#3]
Lets say I have a list of onboardings, I'd like to spawn on initial display. Then I could use something like this:

```dart
class _OnboardingFocusState extends State<_OnboardingFocus> {
  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) async {
      for (var element in widget.onboardings) {
        await HelperOrchestrator.of(context).showAnchoredHelper(
            element.anchoredKeyString, element.toAnchoredHelper(context));
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```

Now I would assume the first overlay of the list to be displayed and then after the user dismisses it, the next to be displayed.
Unfortunately this does not seem to be the case as only the last overview gets displayed

**Comment by g-apparence** [comment]
That's strange. 
I'll try to reproduce this. 👍

**Comment by g-apparence** [comment]
Looking further at what you did I noticed an error.
You shouldn't load all anchor in the init state.
Instead you have to : 
- load and show the first overlay
- set the callback on button or anchor to show the next overlay

Thing is that HelperOrchestrator will always show only **one overlay at a time.** So that's a normal behavior. 
Hope this helps.
